export const ON_FACEBOOK_LOGIN_SUCCEED  = 'ON_FACEBOOK_LOGIN_SUCCEED';
export const ON_FACEBOOK_LOGIN_FAILED  = 'ON_FACEBOOK_LOGIN_FAILED';
export const ON_FACEBOOK_LOGIN_CANCELED = 'ON_FACEBOOK_LOGIN_CANCELED';
export const ON_FACEBOOK_LOGOUT_ACTION  = 'ON_FACEBOOK_LOGOUT_ACTION';