export const ON_AREA_OF_INTERESTS_SCENE_WAITING = 'ON_AREA_OF_INTERESTS_SCENE_WAITING';

export const ON_AREA_OF_INTERESTS_USER_LOGIN_DATA = 'ON_AREA_OF_INTERESTS_USER_LOGIN_DATA';

export const TOGGLE_INTEREST_ACTION = 'TOGGLE_INTEREST_ACTION';
export const SET_SELECTED_INTEREST = 'SET_SELECTED_INTEREST';