export const ON_HOME_USER_LOGIN_DATA = 'ON_HOME_USER_LOGIN_DATA';
export const ON_HOME_FETCH_PRODUCED_DATA_SUCCESS = 'ON_HOME_FETCH_PRODUCED_DATA_SUCCESS';
export const ON_HOME_FETCH_PRODUCED_DATA_FAIL = 'ON_HOME_FETCH_PRODUCED_DATA_FAIL';
export const ON_HOME_VIDEO_LIKE_SUCCESS = 'ON_HOME_VIDEO_LIKE_SUCCESS';
