# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Eloyt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Bolts'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'WindowsAzureMessaging'
  
  pod 'RNNotifications'
  
  target 'EloytTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Eloyt-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eloyt-tvOS

  target 'Eloyt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
