# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eloyt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eloyt
  pod 'RNMobileCenter', '~> 0.2.0'
  pod 'MobileCenter', '~> 0.4.0'

  

  target 'EloytTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Eloyt-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eloyt-tvOS

  target 'Eloyt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
