export default {
  CATCHED_PERMISSION: 'CATCHED_PERMISSION',
  CATCHED_RECIPIENTS: 'CATCHED_RECIPIENTS',
  CATCHED_MESSAGE: 'CATCHED_MESSAGE',
  CATCHED_SETTINGS: 'CATCHED_SETTINGS',
  SNAP_QUEUE_FEEDER_LENGTH: 2,
  DOUBLE_PRESS_DELAY: 300,
  QUICK_PRESS_DELAY: 200,
  SNAP_RECORD_SECOND_MIN: 5, // 5 second by default
  SNAP_RECORD_SECOND_MAX: 3 * 60, // 3 min by default
  SNAP_RECORD_MINUTE_MAX: 3,
  SNAP_HASHTAG_COUNT_LIMIT_MIN: 1,
  SNAP_HASHTAG_COUNT_LIMIT_MAX: 3,
  PROFILE_HASHTAGS_LIMIT_MIN: 1,
  PROFILE_HASHTAGS_LIMIT_MAX: 5,
}
