// Facebook
export const ON_FACEBOOK_LOGIN_SUCCEED  = 'ON_FACEBOOK_LOGIN_SUCCEED';
export const ON_FACEBOOK_LOGIN_FAILED   = 'ON_FACEBOOK_LOGIN_FAILED';
export const ON_FACEBOOK_LOGIN_CANCELED = 'ON_FACEBOOK_LOGIN_CANCELED';
export const ON_FACEBOOK_LOGOUT_ACTION  = 'ON_FACEBOOK_LOGOUT_ACTION';
export const ON_FACEBOOK_ACCESS_TOKEN   = 'ON_FACEBOOK_ACCESS_TOKEN';

// Api
export const ON_SSO_LOGIN_SUCCEED = 'ON_SSO_LOGIN_SUCCEED';
export const ON_SSO_LOGIN_FAILED  = 'ON_SSO_LOGIN_FAILED';
export const ON_SSO_USER_DATA     = 'ON_SSO_USER_DATA';

export const ON_LOGIN_USER_LOGIN_DATA = 'ON_LOGIN_USER_LOGIN_DATA';
