export default {
  DOUBLE_PRESS_DELAY: 300,
  SNAP_RECORD_SECOND_MIN: 1, // 5 second by default
  SNAP_RECORD_SECOND_MAX: 3 * 60, // 3 min by default
  SNAP_RECORD_MINUTE_MAX: 3,
  SNAP_HASHTAG_COUNT_LIMIT_MIN: 1,
  SNAP_HASHTAG_COUNT_LIMIT_MAX: 3,
}
